import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()

export default async function handler(req, res) {
	
		let pr=await prisma.shop_property.createMany({
			data: [/* {id:284, name:'Эксплуатационная масса, включая вес АКБ, kg', filter_type:'Checkboxes', type:'String'},
{id:285, name:'Ширина рабочего коридора, Ast (mm)', filter_type:'Checkboxes', type:'String'},
{id:286, name:'Размер задних колес, mm', filter_type:'Checkboxes', type:'String'},
{id:287, name:'Размер передних колес, mm', filter_type:'Checkboxes', type:'String'},
{id:288, name:'Скорость опускания с грузом / без груза, m/s', filter_type:'Checkboxes', type:'String'},
{id:289, name:'Скорость подъема с грузом / без груза, m/s', filter_type:'Checkboxes', type:'String'},
{id:290, name:'Радиус разворота (внешний), мм', filter_type:'Checkboxes', type:'String'},
{id:291, name:'Размер вил ISO 2331, s/e/l (mm)', filter_type:'Checkboxes', type:'String'},
{id:292, name:'Свободный подъем, h2 (mm)', filter_type:'Checkboxes', type:'String'},
{id:293, name:'Тип трансмиссии', filter_type:'Checkboxes', type:'String'},
{id:294, name:'Угол наклона мачты вперед / назад, α/β(°)', filter_type:'Checkboxes', type:'String'},
{id:295, name:'Центр тяжести, c (mm)', filter_type:'Checkboxes', type:'String'},
{id:296, name:'Внешний радиус поворота, Wa (mm)', filter_type:'Checkboxes', type:'String'},
{id:297, name:'Высота мачты при поднятых вилах, h4 (mm)', filter_type:'Checkboxes', type:'String'},
{id:298, name:'Высота надголовного защитного козырька (кабина), h6 (mm)', filter_type:'Checkboxes', type:'String'},
{id:299, name:'Высота подъема вил, h3 (mm)', filter_type:'Checkboxes', type:'String'},
{id:300, name:'Высота при опущенной мачте, h1 (mm)', filter_type:'Checkboxes', type:'String'},
{id:301, name:'Двигатель, л.с.', filter_type:'Checkboxes', type:'String'},
{id:302, name:'Длина до передней части вил, l2 (mm)', filter_type:'Checkboxes', type:'String'},
{id:303, name:'Дорожный просвет по центру колесной базы, m2 (mm)', filter_type:'Checkboxes', type:'String'},
{id:304, name:'Колесная база, y (mm)', filter_type:'Checkboxes', type:'String'},
{id:305, name:'Мощность двигателя в соответствии с DIN ISO 1585, kw', filter_type:'Checkboxes', type:'String'},
{id:306, name:'Номинальная / Остаточная грузоподъемность, Q (kg)', filter_type:'Checkboxes', type:'String'},
{id:307, name:'Номинальная скорость , min', filter_type:'Checkboxes', type:'String'},
{id:308, name:'Общая ширина, b1 (mm)', filter_type:'Checkboxes', type:'String'},
{id:309, name:'Преодолеваемый подъем с грузом / без груза, %', filter_type:'Checkboxes', type:'String'},
{id:310, name:'Тип погрузчика', filter_type:'Checkboxes', type:'String'},
{id:311, name:'Грузоподъемность (кг)', filter_type:'Checkboxes', type:'String'},
{id:312, name:'Центр загрузки (мм)', filter_type:'Checkboxes', type:'String'},
{id:313, name:'Высота подъема (мм)', filter_type:'Checkboxes', type:'String'},
{id:314, name:'Вес (кг)', filter_type:'Checkboxes', type:'String'},
{id:315, name:'Высота погрузчика (мм)', filter_type:'Checkboxes', type:'String'},
{id:316, name:'Длина до спинки вил (мм)', filter_type:'Checkboxes', type:'String'},
{id:317, name:'Дорожный просвет (мм)', filter_type:'Checkboxes', type:'String'},
{id:318, name:'Минимальный рабочий коридор (AST, мм)', filter_type:'Checkboxes', type:'String'},
{id:319, name:'Передние', filter_type:'Checkboxes', type:'String'},
{id:320, name:'Задние', filter_type:'Checkboxes', type:'String'},
{id:321, name:'Объем двигателя', filter_type:'Checkboxes', type:'String'},
{id:322, name:'Номинальная мощность', filter_type:'Checkboxes', type:'String'},
{id:323, name:'Производитель (trs)', filter_type:'Checkboxes', type:'String'},
{id:324, name:'Кол-во скоростей вперед/назад', filter_type:'Checkboxes', type:'String'},
{id:325, name:'Номинальная грузоподъемность, кг', filter_type:'Checkboxes', type:'String'},
{id:326, name:'Расстояние до центра нагрузки, мм', filter_type:'Checkboxes', type:'String'},
{id:327, name:'Размер передних шин', filter_type:'Checkboxes', type:'String'},
{id:328, name:'Размер задних шин', filter_type:'Checkboxes', type:'String'},
{id:329, name:'Колеса, количество передних/задних (х-ведомые)', filter_type:'Checkboxes', type:'String'},
{id:330, name:'Наклон мачты/каретки вперед/назад,°', filter_type:'Checkboxes', type:'String'},
{id:331, name:'Высота с опущенной мачтой, мм', filter_type:'Checkboxes', type:'String'},
{id:332, name:'Свободный ход, мм', filter_type:'Checkboxes', type:'String'},
{id:333, name:'Высота с поднятой мачтой, мм', filter_type:'Checkboxes', type:'String'},
{id:334, name:'Высота защитной крышки (кабина), мм', filter_type:'Checkboxes', type:'String'},
{id:335, name:'Габаритная длина, мм', filter_type:'Checkboxes', type:'String'},
{id:336, name:'Длина вил, мм', filter_type:'Checkboxes', type:'String'},
{id:337, name:'Общая ширина, мм', filter_type:'Checkboxes', type:'String'},
{id:338, name:'Размеры вил, мм', filter_type:'Checkboxes', type:'String'},
{id:339, name:'Дорожный просвет с грузом под мачтой, мм', filter_type:'Checkboxes', type:'String'},
{id:340, name:'Дорожный просвет, центр колесной базы, мм', filter_type:'Checkboxes', type:'String'},
{id:341, name:'Ширина прохода для поддонов 1000х1200 (поперек)', filter_type:'Checkboxes', type:'String'},
{id:342, name:'Ширина прохода для поддонов 800х1200 (в длину)', filter_type:'Checkboxes', type:'String'},
{id:343, name:'Радиус поворота, мм', filter_type:'Checkboxes', type:'String'},
{id:344, name:'Скорость движения с грузом/без груза, км/ч', filter_type:'Checkboxes', type:'String'},
{id:345, name:'Скорость подъема, с грузом/без груза, м/с', filter_type:'Checkboxes', type:'String'},
{id:346, name:'Скорость опускания, с грузом/без груза, м/с', filter_type:'Checkboxes', type:'String'},
{id:347, name:'Преодолеваемый подъем, с грузом/без груза, %', filter_type:'Checkboxes', type:'String'},
{id:348, name:'Крутящий момент, об/мин', filter_type:'Checkboxes', type:'String'},
{id:349, name:'Количество цилиндров/объем, см³', filter_type:'Checkboxes', type:'String'},
{id:350, name:'Станд. токс. двигателя', filter_type:'Checkboxes', type:'String'},
{id:351, name:'Диаметр цилиндра и ход поршня', filter_type:'Checkboxes', type:'String'},
{id:352, name:'Максимальный крутящий момент, Нм(кгсм)', filter_type:'Checkboxes', type:'String'},
{id:353, name:'Мощность двигателя, кВт (л.с.)', filter_type:'Checkboxes', type:'String'},
{id:354, name:'Производитель двигателя (марка)', filter_type:'Checkboxes', type:'String'},
{id:355, name:'Рабочий объём двигателя, см3', filter_type:'Checkboxes', type:'String'},
{id:356, name:'Расчётная частота вращения, об/мин', filter_type:'Checkboxes', type:'String'},
{id:357, name:'Число и расположение цилиндров', filter_type:'Checkboxes', type:'String'},
{id:358, name:'Топливный бак, л', filter_type:'Checkboxes', type:'String'},
{id:359, name:'Колея передних/ задних колес, мм', filter_type:'Checkboxes', type:'String'},
{id:360, name:'Число передач КП', filter_type:'Checkboxes', type:'String'},
{id:361, name:'Вид рабочего органа', filter_type:'Checkboxes', type:'String'},
{id:362, name:'Размер рабочего органа, ДхШхВ, мм', filter_type:'Checkboxes', type:'String'},
{id:363, name:'Грузоподъёмность, кг', filter_type:'Checkboxes', type:'String'},
{id:364, name:'Общий вес, кг', filter_type:'Checkboxes', type:'String'},
{id:365, name:'Длина до спинки вил, мм', filter_type:'Checkboxes', type:'String'},
{id:366, name:'Дорожный просвет, мм', filter_type:'Checkboxes', type:'String'},
{id:367, name:'Колесная (гусеничная) база, мм', filter_type:'Checkboxes', type:'String'},
{id:368, name:'Мачта, мм', filter_type:'Checkboxes', type:'String'},
{id:369, name:'Наклон мачты (a/b), град', filter_type:'Checkboxes', type:'String'},
{id:370, name:'Свободная высота подъема груза, мм', filter_type:'Checkboxes', type:'String'},
{id:371, name:'Центр тяжести груза, мм', filter_type:'Checkboxes', type:'String'},
{id:372, name:'Ширина рабочего коридора, мм', filter_type:'Checkboxes', type:'String'},
{id:373, name:'Максимальная скорость, км/ч', filter_type:'Checkboxes', type:'String'},
{id:374, name:'Скорость опускания с грузом/без груза, мм/с', filter_type:'Checkboxes', type:'String'},
{id:375, name:'Скорость подъема с грузом/без груза, мм/с', filter_type:'Checkboxes', type:'String'},
{id:376, name:'Наибольший преодолеваемый подъем, град.', filter_type:'Checkboxes', type:'String'},
{id:377, name:'Наружный габаритный радиус поворота, мм', filter_type:'Checkboxes', type:'String'},
{id:378, name:'Высота подъёма рабочего органа, мм', filter_type:'Checkboxes', type:'String'},
{id:379, name:'Максимальная сила тяги, кН', filter_type:'Checkboxes', type:'String'},
{id:380, name:'Аккумуляторы (напряжение/емкость) , В/Ач', filter_type:'Checkboxes', type:'String'},
{id:381, name:'Высота подъем (мм)', filter_type:'Checkboxes', type:'String'},
{id:382, name:'Габариты', filter_type:'Checkboxes', type:'String'},
{id:383, name:'Скорость перемещения', filter_type:'Checkboxes', type:'String'},
{id:384, name:'Скорость подъёма/опускания груза', filter_type:'Checkboxes', type:'String'},
{id:385, name:'Вес, кг', filter_type:'Checkboxes', type:'String'},
{id:386, name:'Скорость движения вперед/назад, км/ч', filter_type:'Checkboxes', type:'String'},
{id:387, name:'Rated capacity/rated load', filter_type:'Checkboxes', type:'String'},
{id:388, name:'Load centre distance', filter_type:'Checkboxes', type:'String'},
{id:389, name:'Load distance, centre of drive axle to fork', filter_type:'Checkboxes', type:'String'},
{id:390, name:'Rear overhang', filter_type:'Checkboxes', type:'String'},
{id:391, name:'Wheelbase', filter_type:'Checkboxes', type:'String'},
{id:392, name:'Service Weight', filter_type:'Checkboxes', type:'String'},
{id:393, name:'Axle loading, laden front/rear', filter_type:'Checkboxes', type:'String'},
{id:394, name:'Axle loading, unladen front/rear', filter_type:'Checkboxes', type:'String'},
{id:395, name:'Tread, front', filter_type:'Checkboxes', type:'String'},
{id:396, name:'Tread, rear', filter_type:'Checkboxes', type:'String'},
{id:397, name:'Tilt of mast/fork carriage forward/backward', filter_type:'Checkboxes', type:'String'},
{id:398, name:'Height, mast lowered', filter_type:'Checkboxes', type:'String'},
{id:399, name:'Free lift', filter_type:'Checkboxes', type:'String'},
{id:400, name:'Lift', filter_type:'Checkboxes', type:'String'},
{id:401, name:'Height, mast extended', filter_type:'Checkboxes', type:'String'},
{id:402, name:'Height of overhead guard （cabin）', filter_type:'Checkboxes', type:'String'},
{id:403, name:'Length to face of forks', filter_type:'Checkboxes', type:'String'},
{id:404, name:'Overall', filter_type:'Checkboxes', type:'String'},
{id:405, name:'Fork dimensions ISO 2331', filter_type:'Checkboxes', type:'String'},
{id:406, name:'Ground clearance, laden, below mast', filter_type:'Checkboxes', type:'String'},
{id:407, name:'Ground clearance, centre of wheelbase', filter_type:'Checkboxes', type:'String'},
{id:408, name:'Turning radius', filter_type:'Checkboxes', type:'String'},
{id:409, name:'Min. right angle stacking aisle  (Add load length and clearance)', filter_type:'Checkboxes', type:'String'},
{id:410, name:'Travel speed, laden/unladen', filter_type:'Checkboxes', type:'String'},
{id:411, name:'Lift speed, laden/unladen', filter_type:'Checkboxes', type:'String'},
{id:412, name:'Lowering speed, laden/unladen', filter_type:'Checkboxes', type:'String'},
{id:413, name:'Drawbar pull, laden/unladen', filter_type:'Checkboxes', type:'String'},
{id:414, name:'Gradeability, laden/unladen', filter_type:'Checkboxes', type:'String'},
{id:415, name:'Engine power according to DIN ISO 1585', filter_type:'Checkboxes', type:'String'},
{id:416, name:'Rated speed', filter_type:'Checkboxes', type:'String'},
{id:417, name:'Number of cylinders/displacement', filter_type:'Checkboxes', type:'String'},
{id:418, name:'Battery voltage/nominal capacity', filter_type:'Checkboxes', type:'String'},
{id:419, name:'Rated torque', filter_type:'Checkboxes', type:'String'},
{id:420, name:'Bore x stroke', filter_type:'Checkboxes', type:'String'},
{id:421, name:'Operating pressure for attachments', filter_type:'Checkboxes', type:'String'},
{id:422, name:'Fuel tank capacity', filter_type:'Checkboxes', type:'String'},
{id:423, name:'Максимальная высота подъема, мм', filter_type:'Checkboxes', type:'String'},
{id:424, name:'Вид управления', filter_type:'Checkboxes', type:'String'},
{id:425, name:'Полное название', filter_type:'Checkboxes', type:'String'},
{id:426, name:'Длина погрузчика (мм)', filter_type:'Checkboxes', type:'String'},
{id:427, name:'VFHM 600 (одинарная, свободный ход)', filter_type:'Checkboxes', type:'String'},
{id:428, name:'VFHM 700 (сдвоенная, свободный ход)', filter_type:'Checkboxes', type:'String'},
{id:429, name:'Вилочная тележка, DIN 15173 - ISO2328', filter_type:'Checkboxes', type:'String'},
{id:430, name:'Высота подъема (mm)', filter_type:'Checkboxes', type:'String'},
{id:431, name:'Высота подъема мачты (мм)', filter_type:'Checkboxes', type:'String'},
{id:432, name:'Количество штабелируемых контейнеров (DC/HC)', filter_type:'Checkboxes', type:'String'},
{id:433, name:'Эксплуатационная масса вкл.АКБ, кг', filter_type:'Checkboxes', type:'String'},
{id:434, name:'Макс. преодолеваемый уклон, % / °', filter_type:'Checkboxes', type:'String'},
{id:435, name:'Система управления', filter_type:'Checkboxes', type:'String'},
{id:436, name:'Электродвигатель движения/подъема', filter_type:'Checkboxes', type:'String'},
{id:437, name:'Емкость стандартной АКБ, В/Ач', filter_type:'Checkboxes', type:'String'},
{id:438, name:'АКБ и зарядное устройство', filter_type:'Checkboxes', type:'String'},
{id:439, name:'Приводной (кВт)', filter_type:'Checkboxes', type:'String'},
{id:440, name:'Двигатель гидронасоса', filter_type:'Checkboxes', type:'String'},
{id:441, name:'Стандартная (В/Ач)', filter_type:'Checkboxes', type:'String'},
{id:442, name:'Тип контроллера', filter_type:'Checkboxes', type:'String'},
{id:443, name:'Система привода', filter_type:'Checkboxes', type:'String'},
{id:444, name:'Производитель контролер', filter_type:'Checkboxes', type:'String'},
{id:445, name:'Мачта дуплекс без СВХ', filter_type:'Checkboxes', type:'String'},
{id:446, name:'АКБ кислотная', filter_type:'Checkboxes', type:'String'},
{id:447, name:'Встроенное ЗУ', filter_type:'Checkboxes', type:'String'},
{id:448, name:'Вилы', filter_type:'Checkboxes', type:'String'},
{id:449, name:'Скорость движения с грузом / без', filter_type:'Checkboxes', type:'String'},
{id:450, name:'Рабочий коридор с паллетой 1200*800', filter_type:'Checkboxes', type:'String'},
{id:451, name:'Общая длина', filter_type:'Checkboxes', type:'String'},
{id:452, name:'Вилы, длина/внешний габарит', filter_type:'Checkboxes', type:'String'},
{id:453, name:'Двигатель хода', filter_type:'Checkboxes', type:'String'},
{id:454, name:'Двигатель подъема', filter_type:'Checkboxes', type:'String'},
{id:455, name:'Напряжение / емкость батареи', filter_type:'Checkboxes', type:'String'},
{id:456, name:'Эксплуатационная масса ( с АКБ)', filter_type:'Checkboxes', type:'String'},
{id:457, name:'Грузоподъемность на опорных консолях', filter_type:'Checkboxes', type:'String'},
{id:458, name:'Грузоподъемность на вилах', filter_type:'Checkboxes', type:'String'},
{id:459, name:'Высота подъема опорных консолей', filter_type:'Checkboxes', type:'String'},
{id:460, name:'Высота сложенной мачты', filter_type:'Checkboxes', type:'String'},
{id:461, name:'Вилы, длина / внешний габарит', filter_type:'Checkboxes', type:'String'},
{id:462, name:'Высота подъема*', filter_type:'Checkboxes', type:'String'},
{id:463, name:'Эксплуатационная масса ( с АКБ)**', filter_type:'Checkboxes', type:'String'},
{id:464, name:'Грузоподъемность (2 паллеты) на вилах + консолях', filter_type:'Checkboxes', type:'String'},
{id:465, name:'Высота подъема вил*', filter_type:'Checkboxes', type:'String'},
{id:466, name:'Центр тяжести*', filter_type:'Checkboxes', type:'String'},
{id:467, name:'Рабочий коридор с паллетой 1000*1200 поперек', filter_type:'Checkboxes', type:'String'},
{id:468, name:'Рабочий коридор с паллетой 800*1200 вдоль', filter_type:'Checkboxes', type:'String'},
{id:469, name:'Ширина максимальная', filter_type:'Checkboxes', type:'String'},
{id:470, name:'Высота сложенной мачты*', filter_type:'Checkboxes', type:'String'},
{id:471, name:'Проезд для разворота с паллетой 1200*800', filter_type:'Checkboxes', type:'String'},
{id:472, name:'Рабочий коридор с паллетой 2х800*1200 вдоль*', filter_type:'Checkboxes', type:'String'},
{id:473, name:'Радиус поворота*', filter_type:'Checkboxes', type:'String'},
{id:474, name:'Вилы, длина/внешний габарит **', filter_type:'Checkboxes', type:'String'},
{id:475, name:'Грузоподъемность общая', filter_type:'Checkboxes', type:'String'},
{id:476, name:'Высота подъема платформы', filter_type:'Checkboxes', type:'String'},
{id:477, name:'Максимальная высота подбора заказов', filter_type:'Checkboxes', type:'String'},
{id:478, name:'Длина общая', filter_type:'Checkboxes', type:'String'},
{id:479, name:'Дополнительный подъем вил (эрголифт)', filter_type:'Checkboxes', type:'String'},
 */
			]
		})
	    console.log(pr)


	
  res.status(200).json({ data: req.body })
}
